# Generated by Django 4.2.6 on 2023-10-26 21:51

from decimal import Decimal
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to=posts.models.get_upload_to),
                ),
                ("caption", models.TextField(blank=True, max_length=500)),
                (
                    "post_rate",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
                ),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                (
                    "total_rating_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=100
                    ),
                ),
            ],
        ),
    ]
