# Generated by Django 4.2.6 on 2023-10-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="posts/")),
                ("description", models.TextField(max_length=500)),
                (
                    "post_rate",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
                ),
                ("uuid", models.UUIDField()),
            ],
        ),
    ]
