# Generated by Django 4.2.6 on 2023-10-26 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="uuid",
        ),
    ]
