# Generated by Django 4.2.6 on 2023-10-27 16:10

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to=posts.models.get_upload_to),
        ),
    ]
