# Generated by Django 4.2.6 on 2023-10-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_remove_post_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
