# Generated by Django 4.2.6 on 2023-10-26 08:30

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="description",
            new_name="caption",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to=posts.models.get_upload_to),
        ),
    ]
