# Generated by Django 4.2.6 on 2023-10-26 09:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_rename_description_post_caption_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="total_rating_value",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.00"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="total_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
