# Generated by Django 4.2.6 on 2023-10-26 08:30

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(upload_to=profiles.models.get_upload_to),
        ),
    ]
