# Generated by Django 4.2.6 on 2023-10-25 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_remove_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="rate",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="profile",
            name="unique_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
