# Generated by Django 4.2.6 on 2023-10-27 16:18

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default-user-image.png",
                upload_to=profiles.models.get_upload_to_avatar,
            ),
        ),
    ]
