# Generated by Django 4.2.6 on 2023-10-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_remove_profile_name_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="total_voted",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
